"""initial schema

Revision ID: 12bf2097579f
Revises: 
Create Date: 2026-03-18 14:22:26.758256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bf2097579f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('passenger_name', sa.String(length=255), nullable=False),
    sa.Column('passenger_email', sa.String(length=255), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('total_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seat_count > 0', name='chk_booking_seat_count_positive'),
    sa.CheckConstraint('total_price_minor > 0', name='chk_booking_total_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_flight_id'), 'bookings', ['flight_id'], unique=False)
    op.create_index(op.f('ix_bookings_passenger_email'), 'bookings', ['passenger_email'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_passenger_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_flight_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
