"""initial schema

Revision ID: 522099d71476
Revises: 
Create Date: 2026-03-18 14:42:41.760711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522099d71476'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline_code', sa.String(length=10), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DEPARTED', 'CANCELLED', 'COMPLETED', name='flight_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arrival_at > departure_at', name='chk_flight_arrival_after_departure'),
    sa.CheckConstraint('available_seats <= total_seats', name='chk_flight_available_seats_le_total'),
    sa.CheckConstraint('available_seats >= 0', name='chk_flight_available_seats_non_negative'),
    sa.CheckConstraint('origin_iata <> destination_iata', name='chk_flight_route_not_same'),
    sa.CheckConstraint('price > 0', name='chk_flight_price_positive'),
    sa.CheckConstraint('total_seats > 0', name='chk_flight_total_seats_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number', 'flight_date', name='uq_flight_number_date')
    )
    op.create_index(op.f('ix_flights_departure_at'), 'flights', ['departure_at'], unique=False)
    op.create_index(op.f('ix_flights_destination_iata'), 'flights', ['destination_iata'], unique=False)
    op.create_index(op.f('ix_flights_flight_date'), 'flights', ['flight_date'], unique=False)
    op.create_index(op.f('ix_flights_origin_iata'), 'flights', ['origin_iata'], unique=False)
    op.create_index(op.f('ix_flights_status'), 'flights', ['status'], unique=False)
    op.create_table('seat_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', 'EXPIRED', name='reservation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seat_count > 0', name='chk_seat_reservation_count_positive'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_reservations_booking_id'), 'seat_reservations', ['booking_id'], unique=True)
    op.create_index(op.f('ix_seat_reservations_flight_id'), 'seat_reservations', ['flight_id'], unique=False)
    op.create_index(op.f('ix_seat_reservations_status'), 'seat_reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_reservations_status'), table_name='seat_reservations')
    op.drop_index(op.f('ix_seat_reservations_flight_id'), table_name='seat_reservations')
    op.drop_index(op.f('ix_seat_reservations_booking_id'), table_name='seat_reservations')
    op.drop_table('seat_reservations')
    op.drop_index(op.f('ix_flights_status'), table_name='flights')
    op.drop_index(op.f('ix_flights_origin_iata'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_date'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination_iata'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure_at'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
